public class BatchTimer {
    //public static void scheduleBatch(){
       // string cronExpression = '0 0 0 * * ?';
        //Datetime one = Datetime.now().addMinutes(1);
        //string cronExpression = one.second() + ' ' + one.minute() + ' ' + one.day() + ' ' + one.month() + ' ' + one.year();
        //DeleteHistoricalLoanRecordsBatch batch = new DeleteHistoricalLoanRecordsBatch();
        //Id jobId = Database.executeBatch(batch, 200);
        //System.debug('Batch Job Id: ' + jobId);
    //}
}